
package Vistas;

import java.awt.Dimension;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JInternalFrame;


public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktop = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        Opcion = new javax.swing.JMenu();
        opSalir = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        opRVenta = new javax.swing.JMenuItem();
        mCliente = new javax.swing.JMenu();
        opCliente = new javax.swing.JMenuItem();
        mProducto = new javax.swing.JMenu();
        opProducto = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        opVendedor = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        opVentaSemana = new javax.swing.JMenuItem();
        opClienteFrecuente = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout desktopLayout = new javax.swing.GroupLayout(desktop);
        desktop.setLayout(desktopLayout);
        desktopLayout.setHorizontalGroup(
            desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 726, Short.MAX_VALUE)
        );
        desktopLayout.setVerticalGroup(
            desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 355, Short.MAX_VALUE)
        );

        Opcion.setText("Opciones");
        Opcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OpcionActionPerformed(evt);
            }
        });

        opSalir.setText("Salir");
        opSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opSalirActionPerformed(evt);
            }
        });
        Opcion.add(opSalir);

        jMenuBar1.add(Opcion);

        jMenu2.setText("Ventas");

        opRVenta.setText("Realizar Venta");
        opRVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opRVentaActionPerformed(evt);
            }
        });
        jMenu2.add(opRVenta);

        jMenuBar1.add(jMenu2);

        mCliente.setText("Clientes");

        opCliente.setText("Ver clientes");
        opCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opClienteActionPerformed(evt);
            }
        });
        mCliente.add(opCliente);

        jMenuBar1.add(mCliente);

        mProducto.setText("Productos");

        opProducto.setText("Ver productos");
        opProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opProductoActionPerformed(evt);
            }
        });
        mProducto.add(opProducto);

        jMenuBar1.add(mProducto);

        jMenu5.setText("Vendedor");

        opVendedor.setText("Ver Vendedor");
        opVendedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opVendedorActionPerformed(evt);
            }
        });
        jMenu5.add(opVendedor);

        jMenuBar1.add(jMenu5);

        jMenu6.setText("Reportes");
        jMenu6.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jMenu6ItemStateChanged(evt);
            }
        });
        jMenu6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu6ActionPerformed(evt);
            }
        });

        opVentaSemana.setText("Ventas de la Semana");
        opVentaSemana.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opVentaSemanaActionPerformed(evt);
            }
        });
        jMenu6.add(opVentaSemana);

        opClienteFrecuente.setText("Compras Clientes");
        opClienteFrecuente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opClienteFrecuenteActionPerformed(evt);
            }
        });
        jMenu6.add(opClienteFrecuente);

        jMenuBar1.add(jMenu6);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktop)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktop)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void opSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_opSalirActionPerformed

    private void OpcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OpcionActionPerformed

    }//GEN-LAST:event_OpcionActionPerformed

    private void opRVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opRVentaActionPerformed
        VentasForm vf = new VentasForm();
        Centrar(vf);
    }//GEN-LAST:event_opRVentaActionPerformed

    private void opClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opClienteActionPerformed
        ClientesForm vf = new ClientesForm();
        Centrar(vf);
    }//GEN-LAST:event_opClienteActionPerformed

    private void opProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opProductoActionPerformed
        ProductosForm vf = new ProductosForm();
        Centrar(vf);
    }//GEN-LAST:event_opProductoActionPerformed

    private void opVendedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opVendedorActionPerformed
        VendedorForm vf = new VendedorForm();
        Centrar(vf);
    }//GEN-LAST:event_opVendedorActionPerformed

    private void jMenu6ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jMenu6ItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu6ItemStateChanged

    private void opVentaSemanaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opVentaSemanaActionPerformed
        VentaSemanaForm vsf;
        try {
            vsf = new VentaSemanaForm();
            Centrar(vsf);
        } catch (SQLException e) {
            System.err.println("Error: " + e.getMessage());
        }

    }//GEN-LAST:event_opVentaSemanaActionPerformed

    private void jMenu6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu6ActionPerformed

    }//GEN-LAST:event_jMenu6ActionPerformed

    private void opClienteFrecuenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opClienteFrecuenteActionPerformed
       CompraClienteForm ccf;
        try {
            ccf = new CompraClienteForm();
            Centrar(ccf);
        } catch (SQLException e) {
            System.err.println("Error: " + e.getMessage());
        }
    }//GEN-LAST:event_opClienteFrecuenteActionPerformed

    void Centrar(JInternalFrame frame) {
        desktop.add(frame);
        frame.show();
    }
    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Opcion;
    public static javax.swing.JDesktopPane desktop;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu mCliente;
    private javax.swing.JMenu mProducto;
    private javax.swing.JMenuItem opCliente;
    private javax.swing.JMenuItem opClienteFrecuente;
    private javax.swing.JMenuItem opProducto;
    private javax.swing.JMenuItem opRVenta;
    private javax.swing.JMenuItem opSalir;
    private javax.swing.JMenuItem opVendedor;
    private javax.swing.JMenuItem opVentaSemana;
    // End of variables declaration//GEN-END:variables
}
